.\" Manpage for TeamOp
.TH man "03 July 2025" "1.0" "TeamOp man page"
.SH NAME
TeamOp
.SH DESCRIPTION
simeis est un jeux API ou chaque joueur est cree avec une station spatiale et des credits, son but est d'assembler une flotte et un équipage pour aller farmer des ressourrces
TeamOp est une equipe (de 1) qui apprend la CI/CD à travers des TP utilisant ce jeu comme base.
.SH BUGS
Aucun
.SH AUTHOR
Yvelin-officiel