name : Quality

# TRIGGER
on: [pull_request]

# JOBS
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo check
      - run: cargo fmt -- --check
      - run: cargo clippy --
      - run: cargo test

  target_branch_check:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.base_ref, 'release/') && (github.head_ref == 'main' || startsWith(github.head_ref, 'bug/')) }}
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "La branche source de la PR doit être `main` ou une branche de bug quand la branche cible est une release."