name: Release on PR to release branch
on:
  pull_request:
    branches:
    - release/*
  push:
    branches:
      - release/*

permissions:
  contents: write

env:
  TEST_TAG: user/app:test
  LATEST_TAG: user/app:latest

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build release
        run: cargo build --release

      - name: Prepare Debian package structure
        run: |
          mkdir -p TeamOp/usr/bin
          cp target/release/simeis-server TeamOp/usr/bin/
          cp -r DEBIAN TeamOp/

          chmod 755 TeamOp/DEBIAN/preinst
          chmod 755 TeamOp/DEBIAN/postinst

      - name: Create Debian package
        run: |
          dpkg-deb --build TeamOp TeamOp.deb

      - name: upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: TeamOp-deb
          path: TeamOp.deb

      - name: Build Docker image
        run: |
          docker build -f .github/Dockerfile -t simeis-server:release .

      - name: Save Docker image 
        run: |
          docker image save simeis-server:release -o simeis-server-image.tar

      - name: Upload Docker image 
        uses: actions/upload-artifact@v4
        with:
          name: simeis-server-docker-image
          path: simeis-server-image.tar

      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GIT_HASH }}
          prerelease: true
          name: "Commit ${{ env.GIT_HASH }}"
          body: |
            Built from commit ${{ env.GIT_HASH }} by @${{ github.actor }}
            ${{ env.GIT_MESSAGE }}
          files: |
            target/release/simeis-server
            TeamOp.deb
            simeis-server-image.tar
          clear_attachments: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}