name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    # Pas de dépendences pour l'instant

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build 

  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: typst-community/setup-typst@v3
      - uses: actions/checkout@v4
      - run: make manual
    